language: go

go:
    - 1.13
    - 1.12
    - 1.11
    - 1.10
    - 1.9
    - 1.8
    - 1.7
    - 1.6
    - 1.5
    - 1.4
    - 1.3
    - 1.2
    - 1.1
    - 1

before_install:
    - export TZ=Europe/Kiev

script:
    - make
